using Newtonsoft.Json;
using SensusService.Probes;
using System;

namespace SensusService
{
    /// <summary>
    /// A single unit of sensed information returned by a probe.
    /// </summary>
    public abstract class Datum
    {
        private string _id;
        private string _deviceId;
        private string _probeType;
        private DateTimeOffset _timestamp;
        private int _hashCode;

        public string Id
        {
            get { return _id; }
            set
            {
                _id = value;
                _hashCode = _id.GetHashCode();
            }
        }

        public string DeviceId
        {
            get { return _deviceId; }
            set { _deviceId = value; }
        }

        public string ProbeType
        {
            get { return _probeType; }
            set { _probeType = value; }
        }

        public DateTimeOffset Timestamp
        {
            get { return _timestamp; }
            set { _timestamp = value; }
        }

        [JsonIgnore]
        public abstract string DisplayDetail { get; }

        private Datum() { }  // for JSON.NET deserialization

        public Datum(Probe probe, DateTimeOffset timestamp)
        {
            _probeType = probe == null ? null : probe.GetType().FullName;  // not all data are generated by probes (e.g., reports)
            _timestamp = timestamp;
            _deviceId = SensusServiceHelper.Get().DeviceId;

            Id = Guid.NewGuid().ToString();
        }

        public override int GetHashCode()
        {
            return _hashCode;
        }

        public override bool Equals(object obj)
        {
            return obj is Datum && (obj as Datum)._id == _id;
        }

        public override string ToString()
        {
            return "Type:  " + GetType().Name + Environment.NewLine +
                   "Device ID:  " + _deviceId + Environment.NewLine + 
                   "Probe:  " + _probeType + Environment.NewLine +
                   "Timestamp:  " + _timestamp;
        }
    }
}
